import type { Metadata } from "next";
import "./tailwind.css";
import Navbar from "@/components/navbar";
import { usePathname } from "next/navigation";

export const metadata: Metadata = {
  title: "Vorolabs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
